[notebook]
dir = "~/Documents/Notebook/"

# NOTE SETTINGS
[note]
# This is used to generate slugs or with date formats.
language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"

# Configure random ID generation.
id-charset = "alphanum" # The charset used for random IDs.
id-length = 8 # Length of the generated IDs.
id-case = "lower" # Letter case for the random IDs.

[extra]
author = "Lokesh Mohanty"

[group.journal]
paths = ["journal"]

[group.journal.note]
filename = "{{ format-date now }}"
extension = "md"
template = "journal.md"

[group.standup]
paths = ["standup"]

[group.standup.note]
filename = "{{ format-date now }}"
extension = "md"
template = "standup.md"

[format.markdown]
hashtags = true # Enable support for #hashtags
colon-tags = true # Enable support for :colon:separated:tags:

[tool]
editor = "vi"
shell = "fish"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[lsp.diagnostics]
wiki-title = "hint" # Report titles of wiki-links as hints.
dead-link = "error" # Warn for dead links between notes.
missing-backlink = { level = "warning", position = "bottom" } # Warn when notes link here without backlinks.

[alias]
list = "zk list --quiet $argv"

edlast = "zk edit --limit 1 --sort modified- $argv"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"
log = "zk list --quiet --format path --delimiter0 $argv | xargs -0 git log --patch --"
wc = "zk list --format '{{word-count}}\t{{title}}' --sort word-count $argv"

conf = "vi $HOME/.nix/config/zk/config.toml"

ls = "zk edit --interactive"
lst = "zk edit --interactive --tag $argv"
lsj = 'zk edit "$ZK_NOTEBOOK_DIR/journal" --sort created- --interactive'
lss = 'zk edit "$ZK_NOTEBOOK_DIR/standup" --sort created- --interactive'
ni = 'zk new --no-input "$ZK_NOTEBOOK_DIR/ideas"'
nn = 'zk new --no-input "$ZK_NOTEBOOK_DIR/notes"'
rm = "zk list --interactive --quiet --format path --delimiter0 $argv | xargs -0 rm -vf --"

standup = "zk new --no-input \"$ZK_NOTEBOOK_DIR/standup\""
daily = "zk new --no-input \"$ZK_NOTEBOOK_DIR/journal\""
journal = "zk edit --sort created- journal --interactive"

update = "cd $ZK_NOTEBOOK_DIR; git add -A; git commit -am 'update'; gith push; cd -"
slides = "zk list --interactive --quiet --format path --delimiter0 $argv | xargs -0 slides"


